import { deflateSync, inflateSync, strToU8, strFromU8 } from 'fflate';

// Maximum base64-encoded payload length per tier (characters)
const THRESHOLD_FULL = 200_000;  // machine + services + results
const THRESHOLD_FLOW =  50_000;  // machine + services or machine only

function toBase64Url(u8) {
    const CHUNK = 8192;
    let bin = '';
    for (let i = 0; i < u8.length; i += CHUNK)
        bin += String.fromCharCode(...u8.subarray(i, Math.min(i + CHUNK, u8.length)));
    return btoa(bin).replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
}

function fromBase64Url(s) {
    const bin = atob(s.replace(/-/g, '+').replace(/_/g, '/'));
    const u8  = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) u8[i] = bin.charCodeAt(i);
    return u8;
}

function encode(payload) {
    return toBase64Url(deflateSync(strToU8(JSON.stringify(payload))));
}

export function decodePayload(encoded) {
    return JSON.parse(strFromU8(inflateSync(fromBase64Url(encoded))));
}

/**
 * Build a shareable URL, degrading gracefully by shedding the heaviest layers first:
 *   Tier 1: machine + services + results  (≤ THRESHOLD_FULL)
 *   Tier 2: machine + services            (≤ THRESHOLD_FLOW)
 *   Tier 3: machine only                  (≤ THRESHOLD_FLOW)
 *   Tier 4: { tooLarge: true }
 *
 * Returns: { url, included: string[] } | { tooLarge: true }
 */
export function buildShareUrl(baseUrl, machineJson, servicesSource, testResults) {
    const ui = { diagramDir: window.getDiagramDir?.() ?? 'TD' };

    if (testResults) {
        const enc = encode({ v: 1, machine: machineJson, services: servicesSource || null, results: testResults, ui });
        if (enc.length <= THRESHOLD_FULL) {
            const included = ['machine'];
            if (servicesSource) included.push('services');
            included.push('results');
            return { url: `${baseUrl}#flow=${enc}`, included };
        }
    }
    if (servicesSource) {
        const enc = encode({ v: 1, machine: machineJson, services: servicesSource, ui });
        if (enc.length <= THRESHOLD_FLOW)
            return { url: `${baseUrl}#flow=${enc}`, included: ['machine', 'services'] };
    }
    const enc = encode({ v: 1, machine: machineJson, ui });
    if (enc.length <= THRESHOLD_FLOW)
        return { url: `${baseUrl}#flow=${enc}`, included: ['machine'] };

    return { tooLarge: true };
}

/**
 * Extract the encoded flow payload from a full URL or raw fragment.
 * Allows loading a shared URL generated by a different instance.
 * Accepts:
 *   https://other-host/path/#flow=ABC   → 'ABC'
 *   #flow=ABC                           → 'ABC'
 *   flow=ABC                            → 'ABC'
 * Returns null if no valid flow fragment is found.
 */
export function extractFlowFragment(input) {
    if (!input) return null;
    input = input.trim();
    try {
        const hash = new URL(input).hash;
        if (hash.startsWith('#flow=')) return hash.slice(6);
    } catch (_) {}
    if (input.startsWith('#flow=')) return input.slice(6);
    if (input.startsWith('flow='))  return input.slice(5);
    return null;
}

export function loadFromHash() {
    const hash = window.location.hash;
    if (!hash.startsWith('#flow=')) return null;
    try {
        return decodePayload(hash.slice(6));
    } catch (e) {
        console.error('⚠️  Failed to decode #flow= hash:', e.message);
        return null;
    }
}
